# Generated by Django 5.2.2 on 2025-06-12 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit phone number.')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('location', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
    ]
